### ISSUE TITLE
SyntaxError when installing

### ISSUE THREAD

**Issue by kokosnuss** [nitesuit/KanWarrior#3]
tuxpad@tuxpad-vm:~/kanwarrior/KanWarrior-master$ node main.js 

/home/tuxpad/kanwarrior/KanWarrior-master/controllers/defaultController.js:59
        taskManager.getAllTasks((taskArray)=> {
                                            ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/tuxpad/kanwarrior/KanWarrior-master/main.js:10:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
tuxpad@tuxpad-vm:~/kanwarrior/KanWarrior-master$ 

Can you help me? What's wrong?

**Comment by Saonela** [comment]
Has to do something with ES6 being used in project. Have you tried updating node/npm ?
